name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: nguyenybin2015/bpc-pos-admin-panel-api:latest
      APP_NAME: bpc-pos-admin-panel-api
      ENV_DIR: /.env/bpc-pos-admin-panel-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create .env file
        run: |
          echo "${{ secrets.FILE_ENV }}" > .env

      - name: Create ECDSA key files
        run: |
          mkdir -p ./keys
          echo "${{ secrets.ECDSA_SECRET }}" > ./ecdsa.key
          echo "${{ secrets.ECDSA_PUBLIC }}" > ./ecdsa.pub

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }} .

      - name: Push Docker image
        run: |
          docker push ${{ env.DOCKER_IMAGE }}

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: SSH into VPS and Deploy
        env:
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        run: |
          ssh -o ProxyCommand="cloudflared access ssh --hostname ${{ secrets.SERVER_HOST }}" ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} '
            mkdir -p "${{ env.ENV_DIR }}"
            cd "${{ env.ENV_DIR }}"

            if [ ! -f .env ]; then
              echo "${{ secrets.FILE_ENV }}" > .env
            fi

            docker stop ${{ env.APP_NAME }} || true
            docker rm ${{ env.APP_NAME }} || true
            docker rmi ${{ env.DOCKER_IMAGE }} || true
            docker pull ${{ env.DOCKER_IMAGE }}
            docker run -it --rm --name ${{ env.APP_NAME }} --env-file .env -p 3300:3000 -d ${{ env.DOCKER_IMAGE }}
          '